api_key: "EMPTY"
api_base: "http://0.0.0.0:12345/v1"
temperature: 0
tools_folder: "/home/sxjiang/myproject/agent/ReCall-OCT/evaluation/stabletoolbench/toolenv2025toolbench"
port: 2224
model: MirrorAPI-Cache